version: "3.9"
services:
  jwcbackend:
    image: quay.io/kurama/jwc-backend:main
    restart: always
    labels:
      - traefik.http.routers.admin.rule=Host(`backend.jwcindia.com`)
      - traefik.http.routers.admin.tls=true
      - traefik.http.routers.admin.tls.certresolver=lets-encrypt
      - traefik.port=8001
    networks:
     - internal
     - web
    ports:
      - "8001:8001"
networks:
 web:
   external: true
 internal:
   external: false
