version: "3.9"
services:
  dumdumbackend:
    image: quay.io/kurama/jwc-backend:dumdum
    restart: always
    labels:
      - traefik.backend=dumdumbackend
      - traefik.frontend.rule=Host:dumdum-backend.mamun.cloud
      - traefik.docker.network=web
      - traefik.port=8001
    networks:
     - internal
     - web
    ports:
      - "8001:8001"
networks:
 web:
   external: true
 internal:
   external: false
