version: "3.9"
services:
  omerbackend:
    image: quay.io/kurama/jwc-backend:omer
    restart: always
    labels:
      - traefik.http.routers.admin.rule=Host(`hayath.mamun.cloud`)
      - traefik.http.routers.admin.tls=true
      - traefik.http.routers.admin.tls.certresolver=lets-encrypt
      - traefik.port=8004
    networks:
     - internal
     - web
    ports:
      - "8004:8004"
networks:
 web:
   external: true
 internal:
   external: false